
name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or use 'master' if that's your default branch

jobs:
  build-and-push-react:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push React image
        run: |
          docker build -t praneetha2699/react-frontend:latest ./react-frontend
          docker push praneetha2699/react-frontend:latest

  build-and-push-node:
    runs-on: ubuntu-latest
    needs: build-and-push-react

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Node image
        run: |
          docker build -t praneetha2699/node-backend:latest ./node-backend
          docker push praneetha2699/node-backend:latest
